%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosEventComm_PullSupplier
%% Source: /build/buildd/erlang-14.b.4-dfsg/lib/cosEvent/src/CosEventComm.idl
%% IC vsn: 4.2.27
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSEVENTCOMM_PULLSUPPLIER_HRL).
-define(COSEVENTCOMM_PULLSUPPLIER_HRL, true).




-endif.


