%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosEventChannelAdmin_EventChannel
%% Source: /build/buildd/erlang-14.b.4-dfsg/lib/cosEvent/src/CosEventChannelAdmin.idl
%% IC vsn: 4.2.27
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSEVENTCHANNELADMIN_EVENTCHANNEL_HRL).
-define(COSEVENTCHANNELADMIN_EVENTCHANNEL_HRL, true).




-endif.


