%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosNotifyComm_StructuredPushSupplier
%% Source: /build/buildd/erlang-14.b.4-dfsg/lib/cosNotification/src/CosNotifyComm.idl
%% IC vsn: 4.2.27
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSNOTIFYCOMM_STRUCTUREDPUSHSUPPLIER_HRL).
-define(COSNOTIFYCOMM_STRUCTUREDPUSHSUPPLIER_HRL, true).




-endif.


