%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosNotifyChannelAdmin_EventChannelFactory
%% Source: /build/buildd/erlang-14.b.4-dfsg/lib/cosNotification/src/CosNotifyChannelAdmin.idl
%% IC vsn: 4.2.27
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSNOTIFYCHANNELADMIN_EVENTCHANNELFACTORY_HRL).
-define(COSNOTIFYCHANNELADMIN_EVENTCHANNELFACTORY_HRL, true).




-endif.


