%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_CosNotifyChannelAdmin
%% Source: /build/buildd/erlang-14.b.4-dfsg/lib/cosNotification/src/CosNotifyChannelAdmin.idl
%% IC vsn: 4.2.27
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_COSNOTIFYCHANNELADMIN_HRL).
-define(OE_COSNOTIFYCHANNELADMIN_HRL, true).




-endif.


