%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_CosNotifyFilter
%% Source: /build/buildd/erlang-14.b.4-dfsg/lib/cosNotification/src/CosNotifyFilter.idl
%% IC vsn: 4.2.27
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_COSNOTIFYFILTER_HRL).
-define(OE_COSNOTIFYFILTER_HRL, true).




-endif.


