%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_CosNotification
%% Source: /build/buildd/erlang-14.b.4-dfsg/lib/cosNotification/src/CosNotification.idl
%% IC vsn: 4.2.27
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_COSNOTIFICATION_HRL).
-define(OE_COSNOTIFICATION_HRL, true).




-endif.


