%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_CosNotifyComm
%% Source: /build/buildd/erlang-14.b.4-dfsg/lib/cosNotification/src/CosNotifyComm.idl
%% IC vsn: 4.2.27
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_COSNOTIFYCOMM_HRL).
-define(OE_COSNOTIFYCOMM_HRL, true).




-endif.


