%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosTimerEvent
%% Source: /build/buildd/erlang-14.b.4-dfsg/lib/cosTime/src/CosTimerEvent.idl
%% IC vsn: 4.2.27
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSTIMEREVENT_HRL).
-define(COSTIMEREVENT_HRL, true).


-record('CosTimerEvent_TimerEventT', {utc, event_data}).


-endif.


