%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosTime_TimeService
%% Source: /build/buildd/erlang-14.b.4-dfsg/lib/cosTime/src/CosTime.idl
%% IC vsn: 4.2.27
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSTIME_TIMESERVICE_HRL).
-define(COSTIME_TIMESERVICE_HRL, true).




-endif.


