%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosTimerEvent_TimerEventService
%% Source: /build/buildd/erlang-14.b.4-dfsg/lib/cosTime/src/CosTimerEvent.idl
%% IC vsn: 4.2.27
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSTIMEREVENT_TIMEREVENTSERVICE_HRL).
-define(COSTIMEREVENT_TIMEREVENTSERVICE_HRL, true).




-endif.


