%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: TimeBase
%% Source: /build/buildd/erlang-14.b.4-dfsg/lib/cosTime/src/TimeBase.idl
%% IC vsn: 4.2.27
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(TIMEBASE_HRL).
-define(TIMEBASE_HRL, true).


-record('TimeBase_UtcT', {time, inacclo, inacchi, tdf}).
-record('TimeBase_IntervalT', {lower_bound, upper_bound}).


-endif.


