%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_CosFileTransfer
%% Source: /build/buildd/erlang-14.b.4-dfsg/lib/cosFileTransfer/src/CosFileTransfer.idl
%% IC vsn: 4.2.27
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_COSFILETRANSFER_HRL).
-define(OE_COSFILETRANSFER_HRL, true).




-endif.


